apiVersion: v1
kind: Service
metadata:
  name: flack-app-service
  labels:
    app: flack-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
    name: http
  selector:
    app: flack-app
  type: LoadBalancer
  externalIPs:
  - 192.168.88.230
  - 192.168.88.231
  - 192.168.88.232

---
apiVersion: v1
kind: Service
metadata:
  name: local-db
spec:
  type: ExternalName
  externalName: db.cluster.lan