apiVersion: apps/v1
kind: Deployment
metadata:
  name: flack-app
  labels:
    app: flack-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flack-app
  template:
    metadata:
      labels:
        app: flack-app
    spec:
      containers:
      - name: flack-app
        image: ghcr.io/kaplinale/flack-app:master
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
      imagePullSecrets:
        - name: regcred