apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flack-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: test1.dev.k8s.cluster.lan
    http:
      paths:
      - path: /test1
        pathType: Prefix
        backend:
          service:
            name: flack-app-service
            port:
              number: 80
      - path: /test2
        pathType: Prefix
        backend:
          service:
            name: flack-app-service
            port:
              number: 80
